### PR TITLE
Fix `expiryInSeconds = null` has no effect

### LINKED ISSUE #38: Setting expiryInSeconds to null has no effect
### Environment

- Operating System: `Linux`
- Node Version: `v18.12.1`
- Nuxt Version: `3.0.0`
- Nitro Version: `1.0.0`
- Package Manager: `npm@8.19.2`
- Builder: `vite`
- User Config: `runtimeConfig`, `nitro`, `modules`, `build`, `session`
- Runtime Modules: `@nuxtjs/tailwindcss@6.1.3`, `@sidebase/nuxt-session@0.2.5`
- Build Modules: `-`

### Reproduction

_No response_

### Describe the bug

1. In `nuxt.config.ts` set `session.session.expiryInSeconds` to `null`
2. Start the nuxt application
3. The `moduleOptions` in `ModuleDefinition<ModuleOptions>.setup` will be the default value of `600`

Setting `expiryInSeconds` to another value other than `null` just works fine.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by interpretor**
Closes #38.

Checklist:
- [x] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [x] manually checked my feature / checking not applicable
- [x] wrote tests / testing not applicable
- [x] attached screenshots / screenshot not applicable

Properties with null values aren't copied by `defu`.
As mentioned [here](https://github.com/unjs/defu/issues/12), we would need to exchange `defu` with another module which doesn't ignore null, or change the `expiryInSeconds` option to use false instead of null.

I also changed the `domain` property type, as it is also affected, but currently doesn't make any problems, because null is the default value here.

### CODE REVIEW

File: src/runtime/server/middleware/session/index.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ import { useRuntimeConfig } from '#imports'
 const SESSION_COOKIE_NAME = 'sessionId'
 const safeSetCookie = (event: H3Event, name: string, value: string, createdAt: Date) => {
   const sessionOptions = useRuntimeConfig().session.session as SessionOptions
-  const expirationDate = sessionOptions.expiryInSeconds
+  const expirationDate = sessionOptions.expiryInSeconds !== false
```
Comment (interpretor) [inline src/runtime/server/middleware/session/index.ts:13]: @BracketJohn We should also check here for explicit boolean/false value

**Review by BracketJohn — APPROVED** [review]

File: src/runtime/server/middleware/session/index.ts (hunk 1 above)
Comment (BracketJohn) [reply src/runtime/server/middleware/session/index.ts:13]: yes, good catch

**Review by BracketJohn — APPROVED** [review]
